language: php

php:
  - 5.4

before_script:
  - composer install --prefer-source --dev
  ## PHP_CodeSniffer
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  ## PHP Copy/Paste Detector
  - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
  ## PHP Mess Detector
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash
  ## PHPLOC
  - curl -o phploc.phar https://phar.phpunit.de/phploc.phar

script: 
  - phpunit -c app/ --coverage-text
  ## PHP_CodeSniffer
  - phpcs --standard=PSR1 src/WEILogisticManager/
  - phpcs --standard=PSR2 src/WEILogisticManager/
  ## PHP Copy/Paste Detector
  - php phpcpd.phar --verbose src/WEILogisticManager/
  ## PHP Mess Detector
  - phpmd src/WEILogisticManager/ text codesize,unusedcode,naming,design
  ## PHPLOC
  - php phploc.phar src/WEILogisticManager/

notifications:
  email:
  - c.berezowski@gmail.com
