security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:    .*
            form_login:
                check_path:     fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path : true
                default_target_path: /events
            logout: true
            anonymous: true

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/homepage, role: ROLE_USER }
        - { path: ^/activities, role: ROLE_USER }
        - { path: ^/myfiles, role: ROLE_USER }
        - { path: ^/places, role: ROLE_USER }
        - { path: ^/timetables, role: ROLE_USER }
