_homepage:
    pattern: /
    defaults: { _controller: WEILogisticManagerAdminBundle:Homepage:index }

_admin_events:
    pattern:  /events
    defaults: { _controller: WEILogisticManagerAdminBundle:Events:index }

_admin_events_create:
    pattern:  /events/create
    defaults: { _controller: WEILogisticManagerAdminBundle:Events:create }

_admin_events_udpate:
    pattern:  /events/update/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Events:update }

_admin_events_delete:
    pattern:  /events/delete/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Events:delete }

_admin_events_select:
    pattern:  /events/select/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Events:select }

_admin_files:
    pattern:  /files
    defaults: { _controller: WEILogisticManagerAdminBundle:Files:index }

_admin_places:
    pattern:  /places
    defaults: { _controller: WEILogisticManagerAdminBundle:Places:index }

_admin_places_create:
    pattern:  /places/create
    defaults: { _controller: WEILogisticManagerAdminBundle:Places:create }

_admin_places_update:
    pattern:  /places/update/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Places:update }

_admin_places_delete:
    pattern:  /places/delete/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Places:delete }

_admin_activities:
    pattern:  /activities
    defaults: { _controller: WEILogisticManagerAdminBundle:Activities:index }

_admin_activities_create:
    pattern:  /activities/create
    defaults: { _controller: WEILogisticManagerAdminBundle:Activities:create }

_admin_activities_update:
    pattern:  /activities/update/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Activities:update }

_admin_activities_delete:
    pattern:  /activities/delete/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Activities:delete }

_admin_timetables:
    pattern:  /timetables
    defaults: { _controller: WEILogisticManagerAdminBundle:Timetables:index }
