_homepage:
    pattern: /
    defaults: { _controller: WEILogisticManagerAdminBundle:Connection:index }

_admin_homepage:
    pattern:  /homepage
    defaults: { _controller: WEILogisticManagerAdminBundle:Homepage:index }

_admin_homepage_event_create:
    pattern:  /homepage/event/create
    defaults: { _controller: WEILogisticManagerAdminBundle:Homepage:createEvent }

_admin_homepage_event_udpate:
    pattern:  /homepage/event/update/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Homepage:updateEvent }

_admin_homepage_event_delete:
    pattern:  /homepage/event/delete/{id}
    defaults: { _controller: WEILogisticManagerAdminBundle:Homepage:deleteEvent }

_admin_myfiles:
    pattern:  /myfiles
    defaults: { _controller: WEILogisticManagerAdminBundle:MyFiles:index }

_admin_places:
    pattern:  /places
    defaults: { _controller: WEILogisticManagerAdminBundle:Places:index }

_admin_activities:
    pattern:  /activities
    defaults: { _controller: WEILogisticManagerAdminBundle:Activities:index }

_admin_timetables:
    pattern:  /timetables
    defaults: { _controller: WEILogisticManagerAdminBundle:Timetables:index }
